### ISSUE TITLE
hooks

### ISSUE THREAD

**Issue by rafaelss** [schacon/grack#1]
-----------------------------
$ git remote show local
* remote local
  Fetch URL: http://localhost:3000/grack_test.git
  Push  URL: http://localhost:3000/grack_test.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local ref configured for 'git push':
    master pushes to master (fast-forwardable)
-----------------------------
$ git remote show local2
* remote local2
  Fetch URL: /Users/rafael/projects/grack/projects/grack_test.git
  Push  URL: /Users/rafael/projects/grack/projects/grack_test.git
  HEAD branch: master
  Remote branch:
    master new (next fetch will store in remotes/local2)
  Local ref configured for 'git push':
    master pushes to master (fast-forwardable)
-----------------------------

these two remotes are the same repo, but using different protocols, as you can see. I am trying to configure update/post-receive hooks on this repo, but via http it's not working as expected.

-----------------------------
$ git push local master
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 337 bytes, done.
Total 3 (delta 1), reused 0 (delta 0)
-----------------------------
$ git push local2 master
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 337 bytes, done.
Total 3 (delta 1), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.

some message from hook

error: hook declined to update refs/heads/master
To /Users/rafael/projects/grack/projects/grack_test.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to '/Users/rafael/projects/grack/projects/grack_test.git'
-----------------------------

in the first git push the command simply exits without show any message from update hook, that have this content

-----------------------------
#!/bin/sh

echo
echo "some message from hook"
echo

exit 1
-----------------------------

is it a problem with the protocol or only with grack implementation?

thanks and keep the good work! :)

**Comment by dometto** [comment]
Grack currently doesn't implement hooks. You could do so yourself by implementing a middleware that checks for successful update-pack or receive-pack actions. I might be writing something up like that myself in the near future. If I do I'll drop a note here and put the example in the wiki. In the meantime, anyone else who has a good solution for this, feel free to do the same. :-)
