### ISSUE TITLE
fatal: protocol error: bad line length character

### ISSUE THREAD

**Issue by raw1z** [schacon/grack#12]
Hello,
The GET requests (such as git ls-remote) work well but All the POST requests (such as git clone)  fail with the following error message:

    fatal: protocol error: bad line length character:

My System:

    Windows XP
    Thin v1.2.11
    git v1.7.4

Some logs:

    >> Using rack adapter
    >> Thin web server (v1.2.11 codename Bat-Shit Crazy)
    >> Tracing ON
    >> Maximum connections set to 1024
    >> Listening on 0.0.0.0:8080, CTRL+C to stop
    GET /tpstory/info/refs?service=git-upload-pack HTTP/1.1
    User-Agent: git/1.7.4.3282.g844cb
    Host: localhost:8080
    Accept: */*
    Pragma: no-cache
    
    HTTP/1.1 200 OK
    Content-Type: application/x-git-upload-pack-advertisement
    Expires: Fri, 01 Jan 1980 00:00:00 GMT
    Pragma: no-cache
    Cache-Control: no-cache, max-age=0, must-revalidate
    Content-Length: 256
    Connection: keep-alive
    Server: thin 1.2.11 codename Bat-Shit Crazy
    
    001e# service=git-upload-pack
    0000
    009b86e527191b32b489ed1e75afa930b1915a72b731 HEAD multi_ack thin-pack side-band side-band-64k ofs-delta shallow no-progress include-tag multi_ack_detailed
    003f86e527191b32b489ed1e75afa930b1915a72b731 refs/heads/master
    0000
    POST /tpstory/git-upload-pack HTTP/1.1
    User-Agent: git/1.7.4.3282.g844cb
    Host: localhost:8080
    Accept-Encoding: deflate, gzip
    Content-Type: application/x-git-upload-pack-request
    Accept: application/x-git-upload-pack-result
    Content-Length: 116
    
    0067want 86e527191b32b489ed1e75afa930b1915a72b731 multi_ack_detailed side-band-64k thin-pack ofs-delta
    00000009done
    HTTP/1.1 200 OK
    Content-Type: application/x-git-upload-pack-result
    Connection: close
    Server: thin 1.2.11 codename Bat-Shit Crazy
    
    fatal: protocol error: bad line length character:
    000

Thank you for your help.

**Comment by dometto** [comment]
Probably related to #2, so I'll close this for now. Grit just doesn't play very well with Windows, so the best thing to do would probably be to create a rugged adapter, once rugged supports upload-pack/receive-pack.
