### ISSUE TITLE
Memory Consumption

### ISSUE THREAD

**Issue by runemadsen** [schacon/grack#15]
I'm currently using Grack in production, and it works great. It's running on a 6GB slice, and I'm hosting some rather large repos. When I try to clone one of those repos, the slice runs out of memory. I'm not exactly sure whether it's because of the amount of HTTP calls, the pack-process swallowing up the CPU, or something else, but it's definitely stalling.

Is there anything specific to Grack that can be done about this? Is it generally a no go for huge repos (+1GB)?

**Comment by dometto** [comment]
It's been a while, but can you verify that this issue is resolved for you, @runemadsen?
