### ISSUE TITLE
Exception ArgumentError in Rack body object #each method 

### ISSUE THREAD

**Issue by BAndonovski** [schacon/grack#21]
This is the set up: 
Ruby 1.9
Rails 3.2
Redmine 2.6.1
jbox's redmine_git_hosting plugin

Trying to use git repo through HTTPS. Clone works fine. Push fails because, this is what apache says the issue is: 

App 1013 stderr: [ 2015-02-03 16:33:59.3105 1036/0x0000000782d9b0(Worker 1) utils.rb:68 ]: *** Exception ArgumentError in Rack body object #each method (wrong number of arguments (3 for 1..2)) (process 1036, thread 0x0000000782d9b0(Worker 1)):
App 1013 stderr: 	from /home/r2d2/.bundler/ruby/1.9.1/grack-971b468103ac/lib/grack/server.rb:78:in `popen'
App 1013 stderr: 	from /home/r2d2/.bundler/ruby/1.9.1/grack-971b468103ac/lib/grack/server.rb:78:in `block in service_rpc'
App 1013 stderr: 	from /usr/lib/ruby/vendor_ruby/rack/response.rb:89:in `call'
App 1013 stderr: 	from /usr/lib/ruby/vendor_ruby/rack/response.rb:89:in `each'
App 1013 stderr: 	from /usr/lib/ruby/vendor_ruby/rack/body_proxy.rb:31:in `each'
App 1013 stderr: 	from /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:46:in `each'
App 1013 stderr: 	from /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:460:in `each'
App 1013 stderr: 	from /usr/lib/ruby/vendor_ruby/rack/body_proxy.rb:31:in `each'
App 1013 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:140:in `process_request'
App 1013 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
App 1013 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 1013 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

**Comment by dometto** [comment]
It's not clear to me that this is an issue with grack, since the stack trace points to `utils.rb:68`. Possibly this is a problem with the redmine git hosting plugin?

**Comment by dometto** [comment]
Also, the file `/lib/grack/server.rb` does not exist in this gem. It's probably a customized fork of grack. If you think I'm wrong please reopen this, but I think this doesn't belong in this issue tracker.
