### ISSUE TITLE
Enforcement: More details @ not found

### ISSUE THREAD

**Issue by H3llGhost** [schacon/grack#9]
Hello,

I have installed today grack and tried for 2 hours to get it working til I have read the sourcecode and understand, that I will get the message "not found", when the directory miss, request not supported, etc.
It would be nice, when there is a verbose option, which give me more informations about what is missing.

Thanks.

**Comment by dometto** [comment]
I'll try to document correct usage more explicitly in the readme.

**Comment by bartkamphorst** [comment]
I could be wrong, but I think the request is also for more descriptive error messages.
